repos:
-   repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: debug-statements
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: check-ast
    - id: check-merge-conflict
    - id: check-yaml

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.1
  hooks:
  - id: flake8
    args: ['--exclude=docs/*', '--ignore=E501,W503,E203']

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.8.0
  hooks:
  - id: isort
    additional_dependencies: ['toml']

- repo: https://github.com/python/black
  rev: 20.8b1
  hooks:
    - id: black
